-- File overview: Inserts starter rows so the API has sample data on first run.

-- password_hash is bcrypt of 'password123' for all seed users
INSERT INTO users (name, email, password_hash, role)
VALUES
  ('Ada Lovelace', 'ada@example.com', '$2b$10$dummyHashForSeedDataOnly000000000000000000000000000000', 'admin'),
  ('Grace Hopper', 'grace@example.com', '$2b$10$dummyHashForSeedDataOnly000000000000000000000000000001', 'user'),
  ('Margaret Hamilton', 'margaret@example.com', '$2b$10$dummyHashForSeedDataOnly000000000000000000000000000002', 'user');

INSERT INTO companies (
  name,
  website,
  linkedin,
  industry,
  location,
  description,
  status,
  created_by_user_id,
  approved_by_user_id,
  approved_at
)
VALUES
  ('DabApps', 'https://dabapps.com', 'https://www.linkedin.com/company/dabapps/', 'Web and app agency', 'Brighton', 'Web and app agency.', 'approved', 1, 2, NOW()),
  ('StoryStream', 'https://storystream.ai', 'https://www.linkedin.com/company/storystream/about/', 'Software Development', 'London / Brighton', 'Software development company.', 'approved', 1, 2, NOW()),
  ('Dapper Labs Limited', 'https://wearechaperone.com', 'https://www.linkedin.com/company/dapper-labs-ltd/', 'Software Development', 'Brighton', 'Software development company.', 'approved', 2, 1, NOW()),
  ('Certn', NULL, NULL, NULL, 'Lewes', NULL, 'approved', 1, 2, NOW()),
  ('Rakuten Advertising', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Zivio', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('UX Club', NULL, 'https://www.linkedin.com/company/uxclub.com/people/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Park Cameras', NULL, NULL, NULL, 'Burgess Hill', NULL, 'approved', 1, 2, NOW()),
  ('Stack Adept', NULL, NULL, NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('CoGapp', NULL, 'https://www.linkedin.com/company/cogapp/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Pure360', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('The Flex', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Shopify', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Direct Ferries', NULL, NULL, NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('VET.CT', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('BookWhen Ltd', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Shopa', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('The Student Room Group', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Benchmark Capital', NULL, 'https://www.linkedin.com/company/benchmark-capital-limited/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Yoto', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Alchem Technologies', NULL, 'https://www.linkedin.com/company/alchem-technologies-ltd/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Audioboom', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('The Boxoffice Company', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('CoverageBook', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('American Express', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Designs in Detail', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('tails.com', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Code to Inspire', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Medical Tracker', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('tetloose.com', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('StoreLab', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('INTO University Partnerships', NULL, 'https://www.linkedin.com/school/into-university-partnerships/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Osborne Brook', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Coding Cops', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Cabiri', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Makers Academy', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Charanga Music', NULL, 'https://www.linkedin.com/company/charanga/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Quality Engineer', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Homeflow Ltd', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Morson Edge', NULL, NULL, NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Summit Solutions', NULL, NULL, NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Bookable', NULL, NULL, NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Pegasus', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Wiggle', NULL, NULL, NULL, 'Portsmouth', NULL, 'approved', 1, 2, NOW()),
  ('Elucidat', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Land Tech', NULL, 'https://www.linkedin.com/company/landtechnologies/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Omnify', NULL, 'https://www.linkedin.com/company/5059766/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('ActiveInbox', NULL, 'https://www.linkedin.com/company/activeinbox/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Prolific', NULL, 'https://www.linkedin.com/company/prolific-com/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('T-Plan', NULL, 'https://www.linkedin.com/company/t-plan/', NULL, 'Southwick', NULL, 'approved', 1, 2, NOW()),
  ('Mindlab', NULL, 'https://www.linkedin.com/company/mindlab-international/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('OnPace', NULL, 'https://www.linkedin.com/company/12604340/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Connect Group UK Ltd', NULL, 'https://www.linkedin.com/company/connectgrpuk/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Datanauts', NULL, 'https://www.linkedin.com/company/2739127/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Omnichain Nexus', NULL, 'https://www.linkedin.com/company/omnichain-nexus/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Graphite Digital', NULL, 'https://www.linkedin.com/company/graphite-digital/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Bright', NULL, 'https://www.linkedin.com/company/built-by-bright/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Avtura Limited', NULL, 'https://www.linkedin.com/company/avtura-limited/', NULL, 'Crawley', NULL, 'approved', 1, 2, NOW()),
  ('InCrowd Sports', NULL, 'https://www.linkedin.com/company/incrowd-sports/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Count on Crunch', NULL, 'https://www.linkedin.com/company/countoncrunch/', NULL, 'Hove', NULL, 'approved', 1, 2, NOW()),
  ('Sussex University', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Brighton & Hove Council', NULL, 'https://www.linkedin.com/company/brighton-&-hove-city-council/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Royal Navy', NULL, 'https://www.linkedin.com/company/royalnavy/', NULL, 'Portsmouth', NULL, 'approved', 1, 2, NOW()),
  ('Groundsure', NULL, 'https://www.linkedin.com/company/groundsure/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Brandwatch', NULL, 'https://www.linkedin.com/company/brandwatch/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('John Lewis', NULL, 'https://www.linkedin.com/company/john-lewis-partnership/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('SC Data', NULL, 'https://www.linkedin.com/company/sc-data/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Datatonic', NULL, 'https://www.linkedin.com/company/datatonic/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Breathe', NULL, 'https://www.linkedin.com/company/breathehr/', NULL, 'Horsham', NULL, 'approved', 1, 2, NOW()),
  ('Housetrip', NULL, 'https://www.linkedin.com/company/housetrip/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Trafiq', NULL, 'https://www.linkedin.com/company/trafiq-uk/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Dharmafly', NULL, 'https://www.linkedin.com/company/dharmafly/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('LetAdmin', NULL, 'https://www.linkedin.com/company/letadmin/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Char.gy', NULL, 'https://www.linkedin.com/company/char.gy/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('SO Energy', NULL, 'https://www.linkedin.com/company/so-energy/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Silk Media', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Icon Live Ltd', NULL, NULL, NULL, 'Sussex', NULL, 'approved', 1, 2, NOW()),
  ('Answer The Public', NULL, 'https://www.linkedin.com/company/answerthepublic/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('PropellerNet', NULL, 'https://www.linkedin.com/company/propellernet/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('ivee', NULL, 'https://www.linkedin.com/company/iveejobs/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Sussex Bay', NULL, 'https://www.linkedin.com/company/sussex-bay/', NULL, 'Worthing', NULL, 'approved', 1, 2, NOW()),
  ('Baxter & Bailey', NULL, 'https://www.linkedin.com/company/baxter-and-bailey/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('UnitedUs', NULL, 'https://www.linkedin.com/company/unitedus/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Product Alchemy Ltd', NULL, 'https://www.linkedin.com/company/product-alchemy-ltd/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Virgin Atlantic', NULL, 'https://www.linkedin.com/company/virgin-atlantic-airways/', NULL, 'Crawley', NULL, 'approved', 1, 2, NOW()),
  ('Equal Experts', NULL, 'https://www.linkedin.com/company/equal-experts/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('The Unit (GB) Ltd', NULL, 'https://www.linkedin.com/company/the-unit-gb-ltd/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Headshift', NULL, 'https://www.linkedin.com/company/headshift/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Yardlink', NULL, 'https://www.linkedin.com/company/yardlink/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Futrli', NULL, 'https://www.linkedin.com/company/futrli/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Makemedia', NULL, 'https://www.linkedin.com/company/makemedia/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Frively Ltd', NULL, 'https://www.linkedin.com/company/frively-ltd/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('15Below', NULL, 'https://www.linkedin.com/company/15below/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('FutureLearn', NULL, 'https://www.linkedin.com/company/futurelearn/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Seed Brighton', NULL, 'https://www.linkedin.com/company/seedbrighton/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Campsites.co.uk', NULL, 'https://www.linkedin.com/company/campsites-co-uk/', NULL, 'Haywards Heath', NULL, 'approved', 1, 2, NOW()),
  ('Functional Skills UK Ltd', NULL, 'https://www.linkedin.com/school/functional-skills-uk-ltd/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Seiki Systems Ltd', NULL, 'https://www.linkedin.com/company/seiki-systems-ltd/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Green Lemon Company', NULL, 'https://www.linkedin.com/company/green-lemon-company/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Angry Creative UK', NULL, 'https://www.linkedin.com/company/angrycreative-uk/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Southern Co-op', NULL, 'https://www.linkedin.com/company/the-southern-co-operative/', NULL, 'Portsmouth', NULL, 'approved', 1, 2, NOW()),
  ('Arke', NULL, 'https://www.linkedin.com/company/arkeagency/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Global Media Entertainment Outdoor', NULL, 'https://www.linkedin.com/company/global-media-entertainment-outdoor/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Filmstro', NULL, 'https://www.linkedin.com/company/filmstro/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Meethumara', NULL, 'https://www.linkedin.com/company/meethumara/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Silicon Brighton', NULL, 'https://www.linkedin.com/company/siliconbrighton/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Zoopla', NULL, 'https://www.linkedin.com/company/zoopla/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('Skoosh', NULL, 'https://www.linkedin.com/company/skoosh-international-ltd/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Synapsys Solutions Ltd', NULL, 'https://www.linkedin.com/company/synapsys-solutions/', NULL, 'Burgess Hill', NULL, 'approved', 1, 2, NOW()),
  ('BMW', NULL, 'https://www.linkedin.com/company/bmw-group/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Forloop', NULL, 'https://www.linkedin.com/company/forloop-ltd/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('a8learning', NULL, 'https://www.linkedin.com/company/a8learning/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Zoe Mode', NULL, 'https://www.linkedin.com/company/zoe-mode/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('ByteOne Ltd', 'https://byteone.uk/', NULL, NULL, 'Hove', NULL, 'approved', 1, 2, NOW()),
  ('KILLSTAR', NULL, 'https://www.linkedin.com/company/killstar/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Octopus Energy', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('TRG Technology Recruitment', NULL, 'https://www.linkedin.com/company/trg-recruitment/', NULL, 'London', NULL, 'approved', 1, 2, NOW()),
  ('EDF (UK)', NULL, NULL, NULL, 'Hove', NULL, 'approved', 1, 2, NOW()),
  ('RINA Renewables Consulting', NULL, NULL, NULL, NULL, NULL, 'approved', 1, 2, NOW()),
  ('Stantec', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('INSHUR', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Haskoning', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Mott MacDonald', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Sureserve', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('University of Sussex', NULL, 'https://www.linkedin.com/school/university-of-sussex/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Scoreline', NULL, 'https://www.linkedin.com/company/scorelineai/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Asquared', NULL, 'https://www.linkedin.com/company/asquareduk/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Sussex AI', NULL, 'https://www.linkedin.com/company/sussex-ai/', NULL, 'Falmer', NULL, 'approved', 1, 2, NOW()),
  ('Unity Technologies', 'https://unity.com', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Unusual Technologies', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Institute of Development Studies', NULL, 'https://www.linkedin.com/school/institute-of-development-studies/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Hare Digital', 'https://www.hare.digital', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Aariyatech', 'https://www.aariyatech.co.uk', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('EKO UK Tech', 'https://www.ekouk.com', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Boni Technology', 'https://bonitech.co.uk', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Bright Minded', 'https://brightminded.com', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Cell Software', 'https://cellsoftware.co.uk', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Creative Stack Ltd', NULL, 'https://www.linkedin.com/company/creative-stack-ltd/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('The GelBottle Inc', NULL, 'https://www.linkedin.com/company/the-gelbottle-inc/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('North Building Technologies', 'https://www.northbt.com', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Kraken Tech Ltd', 'https://kraken.tech', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Fantastic Tech', 'https://fantastic.tech', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Cfront', 'https://cfront.co.uk', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Blackwood Creative', NULL, 'https://www.linkedin.com/company/blackwood-creative/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('BIMM University', NULL, 'https://www.linkedin.com/school/bimm-university/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('OneFamily', NULL, 'https://www.linkedin.com/company/onefamily/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Brightec Ltd', 'https://www.brightec.co.uk', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Trident', 'https://www.trident.co.uk', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Carden IT Services', 'https://cardenitservices.co.uk', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Ingenio Tech', 'https://www.ingeniotech.co.uk', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Postjer Agency', NULL, 'https://www.linkedin.com/company/postjeragency/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Dragon Drop', 'https://www.dragondrop.uk/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Amiqus', NULL, 'https://www.linkedin.com/company/10146431/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('1X2 Network', NULL, 'https://www.linkedin.com/company/1x2-network/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Paxton Access', 'https://www.paxton-access.com/', NULL, NULL, 'Sussex', NULL, 'approved', 1, 2, NOW()),
  ('Crunch Accounting', 'https://www.crunch.co.uk/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('BrightLocal', 'https://www.brightlocal.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('West Pier Studio', 'https://www.westpierstudio.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Bozboz', 'https://www.bozboz.co.uk/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Electric Putty', NULL, 'https://www.linkedin.com/company/electric-putty/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Fat Media', NULL, 'https://www.linkedin.com/company/fatmedia-marketing/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Madgex', NULL, 'https://www.linkedin.com/company/madgex/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Wild Dog Design', NULL, 'https://www.linkedin.com/company/wild-dog-design/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Quantuma', 'https://www.quantuma.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Red River', 'https://river.red/', NULL, NULL, 'Horsham', NULL, 'approved', 1, 2, NOW()),
  ('East Sussex Web Designers', 'https://www.eastsussexwebdesigners.com/', NULL, NULL, 'Battle', NULL, 'approved', 1, 2, NOW()),
  ('Madison Solutions', 'http://www.madisonsolutions.co.uk/', NULL, NULL, 'Peacehaven', NULL, 'approved', 1, 2, NOW()),
  ('Iron Mountain', NULL, NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Inviqa', 'https://inviqa.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Weald Computers', 'https://wealdcomputers.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Brighton SEO', 'https://brightonseo.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Kineo', 'https://kineo.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Legal & General', 'https://www.legalandgeneral.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Liquid Light', 'https://www.liquidlight.co.uk/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Brilliant Noise', 'https://brilliantnoise.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Fat Fish Digital', 'https://fatfishdigital.co.uk/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('MPB', 'https://www.mpb.com/en-uk', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Skylark Coffee', NULL, 'https://www.linkedin.com/company/skylark-coffee/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Tillo', 'http://www.tillo.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Wave Community Bank', 'http://www.wavecb.org.uk/', NULL, NULL, 'Hove', NULL, 'approved', 1, 2, NOW()),
  ('East Sussex County Council', NULL, 'https://www.linkedin.com/company/east-sussex-county-council/', NULL, 'Lewes', NULL, 'approved', 1, 2, NOW()),
  ('Varndean College', NULL, 'https://www.linkedin.com/school/varndean-college/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Alirity', 'https://alirity.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Virgin Media O2', NULL, 'https://www.linkedin.com/company/virgin-media-o2/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('FPR Group', NULL, 'https://www.linkedin.com/company/kingdom-people-recruitment/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('FUNNL Ltd', NULL, 'https://www.linkedin.com/company/funnl-ltd/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Curve IT Ltd', 'https://www.curveit.com/', NULL, NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Nested', NULL, 'https://www.linkedin.com/company/nested-insights/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Tide Partnership', NULL, 'https://www.linkedin.com/company/tidepartnership/', NULL, 'Brighton', NULL, 'approved', 1, 2, NOW()),
  ('Adaptive Lab', NULL, 'https://www.linkedin.com/company/adaptive-lab/', NULL, 'London', NULL, 'approved', 1, 2, NOW());

INSERT INTO technologies (name, slug)
VALUES
  ('Python', 'python'),
  ('Django', 'django'),
  ('React', 'react'),
  ('AWS', 'aws'),
  ('Node.js', 'node.js'),
  ('TypeScript', 'typescript');

INSERT INTO company_technologies (company_id, technology_id)
VALUES
  (
    (SELECT id FROM companies WHERE name = 'DabApps'),
    (SELECT id FROM technologies WHERE slug = 'python')
  ),
  (
    (SELECT id FROM companies WHERE name = 'DabApps'),
    (SELECT id FROM technologies WHERE slug = 'django')
  ),
  (
    (SELECT id FROM companies WHERE name = 'DabApps'),
    (SELECT id FROM technologies WHERE slug = 'react')
  ),
  (
    (SELECT id FROM companies WHERE name = 'StoryStream'),
    (SELECT id FROM technologies WHERE slug = 'react')
  ),
  (
    (SELECT id FROM companies WHERE name = 'StoryStream'),
    (SELECT id FROM technologies WHERE slug = 'python')
  ),
  (
    (SELECT id FROM companies WHERE name = 'StoryStream'),
    (SELECT id FROM technologies WHERE slug = 'aws')
  ),
  (
    (SELECT id FROM companies WHERE name = 'Dapper Labs Limited'),
    (SELECT id FROM technologies WHERE slug = 'node.js')
  ),
  (
    (SELECT id FROM companies WHERE name = 'Dapper Labs Limited'),
    (SELECT id FROM technologies WHERE slug = 'typescript')
  );

INSERT INTO job_roles (name, slug)
VALUES
  ('Software Engineer', 'software-engineer'),
  ('Frontend Developer', 'frontend-developer'),
  ('Backend Developer', 'backend-developer'),
  ('Data Engineer', 'data-engineer'),
  ('Full Stack Developer', 'full-stack-developer');

INSERT INTO company_job_roles (company_id, job_role_id)
VALUES
  (
    (SELECT id FROM companies WHERE name = 'DabApps'),
    (SELECT id FROM job_roles WHERE slug = 'software-engineer')
  ),
  (
    (SELECT id FROM companies WHERE name = 'DabApps'),
    (SELECT id FROM job_roles WHERE slug = 'frontend-developer')
  ),
  (
    (SELECT id FROM companies WHERE name = 'StoryStream'),
    (SELECT id FROM job_roles WHERE slug = 'backend-developer')
  ),
  (
    (SELECT id FROM companies WHERE name = 'StoryStream'),
    (SELECT id FROM job_roles WHERE slug = 'data-engineer')
  ),
  (
    (SELECT id FROM companies WHERE name = 'Dapper Labs Limited'),
    (SELECT id FROM job_roles WHERE slug = 'full-stack-developer')
  );